spring:
  application:
    name: bulletin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pozdravliator}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:iamdeadlytired795795}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rmuser}
    password: ${RABBITMQ_PASSWORD:rmpassword}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 5000
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 2000
        multiplier: 2.0
        max-interval: 10000
      default-requeue-rejected: false
  amqp:
    deserialization:
      trust:
        all: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/oAuth}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/oAuth}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:myclient}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:jeWE38sfUCQJhplYyeJ7IwcMk8P27fVh}
            scope: openid

server:
  port: ${SERVER_PORT:8080}